In [1]:
from scipy.optimize import root
import numpy as np

In [9]:
def assign_params(ss_params):
    a_0 = ss_params['a_0']
    a_1 = ss_params['a_1']
    a_2 = ss_params['a_2']
    alf = ss_params['alf']
    delt = ss_params['delt']
    om_0 = ss_params['om_0']
    om_1 = ss_params['om_1']
    om_2 = ss_params['om_2']
    eps = ss_params['eps']
    tht = ss_params['tht']
    bet = ss_params['bet']
    psi_k = ss_params['psi_k']
    psi_n = ss_params['psi_n']
    return eps,tht,alf,bet,om_0,om_1,om_2,delt,psi_k,psi_n,a_0,a_1,a_2



In [10]:
def equations(vars, params):
	n_0,n_1,n_2,s_0,s_1,s_2,k,k_0,k_1,k_2,c_0,c_1,c_2,i = vars
	eps,tht,alf,bet,om_0,om_1,om_2,delt,psi_k,psi_n,a_0,a_1,a_2 = assign_params(params)
	ph=(om_0*c_0**((eps-1)/eps)+om_1*c_1**((eps-1)/eps)+om_2*c_2**((eps-1)/eps)	)**((1-tht*eps)/(eps-1))

	v_0=om_0*c_0**(-1/eps)*ph
	v_1=om_1*c_1**(-1/eps)*ph
	v_2=om_2*c_2**(-1/eps)*ph

	fn_0=np.exp(a_0)*(1-alf)*(s_0/n_0)**alf*k**alf
	fn_1=np.exp(a_1)*(1-alf)*(s_1/n_1)**alf*k**alf
	fn_2=np.exp(a_2)*(1-alf)*(s_2/n_2)**alf*k**alf
 
	fs_0=np.exp(a_0)*alf*(n_0/s_0)**(1-alf)*k**alf
	fs_1=np.exp(a_1)*alf*(n_1/s_1)**(1-alf)*k**alf
	fs_2=np.exp(a_2)*alf*(n_2/s_2)**(1-alf)*k**alf
  
	fk_0=np.exp(a_0)*alf*(s_0/n_0*k)**alf
	fk_1=np.exp(a_1)*alf*(s_1/n_1*k)**alf
	fk_2=np.exp(a_2)*alf*(s_2/n_2*k)**alf
 
	q_0=(1-psi_n/2*(n_0/n_0-1)**2)
	q_1=(1-psi_n/2*(n_1/n_1-1)**2)
	q_2=(1-psi_n/2*(n_2/n_2-1)**2)
 
	x_10=k_0*q_0**(1-alf)-n_0*psi_n/q_0**alf/n_0*(n_0/n_0-1)
	x_11=k_1*q_1**(1-alf)-n_1*psi_n/q_1**alf/n_1*(n_1/n_1-1)
	x_12=k_2*q_2**(1-alf)-n_2*psi_n/q_2**alf/n_2*(n_2/n_2-1)

	x_20=fk_0*psi_n/q_0**alf*(n_0/n_0-1)*(n_0/n_0)**2
	x_21=fk_1*psi_n/q_1**alf*(n_1/n_1-1)*(n_1/n_1)**2
	x_22=fk_2*psi_n/q_2**alf*(n_2/n_2-1)*(n_2/n_2)**2
 
	z_1=1-psi_k*(i/k-delt)
	z_2=1-delt-psi_k/2*(i/k-delt)**2+psi_k*i/k*(i/k-delt)
 
	eq1=n_0+n_1+n_2-1
	eq2=s_0+s_1+s_2-1
	eq3=k_0-s_0/n_0*k
	eq4=k_1-s_1/n_1*k
	eq5=k_2-s_2/n_2*k
	eq6=v_1*x_11*fn_1+v_1*x_21*fn_1-(v_0*x_10*fn_0+v_0*x_20*fn_0)
	eq7=v_2*x_12*fn_2+v_2*x_22*fn_2-(v_0*x_10*fn_0+v_0*x_20*fn_0)
	eq8=v_1*fs_1-v_0*fs_0
	eq9=v_2*fs_2-v_0*fs_0
	eq10=bet*(fs_0/k+z_2/z_1)-(v_0/v_0/z_1)
	eq11=(1-delt)*k+i-psi_k/2*(1/k-delt)**2*k-k
	eq12=c_0-np.exp(a_0)*n_0**(1-alf)*s_0**alf*k**alf-(1-delt)*k+k
	eq13=c_1-np.exp(a_1)*n_1**(1-alf)*s_1**alf*k**alf
	eq14=c_2-np.exp(a_2)*n_2**(1-alf)*s_2**alf*k**alf
	
	return [eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9,eq10,eq11,eq12,eq13,eq14]


In [11]:
initial_guess = [.3,.3,.3,.3,.3,.3,3,.3,.3,.3,.3,.3,.3,0]
def solve_equations(params):
    
    sol = root(equations, initial_guess, args=(ss_params,))
    
    # Extract the solution vector
    n_0,n_1,n_2,s_0,s_1,s_2,k,k_0,k_1,k_2,c_0,c_1,c_2,i = sol.x
    a_0=0
    a_1=0
    a_2=0
    ss_dict = {
    'n_0': n_0,
    'n_1': n_1,
    'n_2': n_2,
    's_0': s_0,
    's_1': s_1,
    's_2': s_2,    
    'k': k,
    'k_0': k_0,
    'k_1': k_1,
    'k_2': k_2,
    'c_0': c_0,
    'c_1': c_1,
    'c_2': c_2,
    'i': i,
    'a_0': a_0,
    'a_1': a_1,
    'a_2': a_2
    }
    return sol, ss_dict
    

# Call the wrapper function
sol, ss_dict=solve_equations(ss_params)
print(sol)
ss_dict


 message: The solution converged.
 success: True
  status: 1
     fun: [-1.110e-16  0.000e+00 ...  8.169e-13 -9.029e-13]
       x: [ 4.368e-01  2.816e-01 ...  8.740e-01  4.816e-01]
    nfev: 42
    fjac: [[-5.560e-02 -5.969e-11 ... -1.278e-03 -5.232e-03]
           [-3.941e-02  3.857e-11 ...  5.439e-02  5.471e-04]
           ...
           [-3.118e-01 -2.372e-01 ... -2.009e-01 -2.498e-01]
           [ 6.222e-02 -6.227e-02 ... -2.961e-04  1.741e-03]]
       r: [-1.799e+01  2.783e-01 ...  4.606e-01  1.500e-01]
     qtf: [-9.314e-13 -1.446e-10 ...  3.518e-12 -1.464e-13]


{'n_0': 0.43678160919544085,
 'n_1': 0.2816091954014113,
 'n_2': 0.28160919540314777,
 's_0': 0.43678160919537834,
 's_1': 0.28160919540206236,
 's_2': 0.2816091954025593,
 'k': 9.631391200953535,
 'k_0': 9.631391200953374,
 'k_1': 9.6313912009534,
 'k_2': 9.631391200953448,
 'c_0': 0.8739595719383363,
 'c_1': 0.8739595719373454,
 'c_2': 0.873959571939091,
 'i': 0.48156956004767615,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [12]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('var \n')
        for key, value in ss_dict.items():
            f.write(f'{key}\n')
        f.write(f';\n\n\n')
        f.write('varexo \n')
        for key, value in ss_shock.items():
            f.write(f'{key}_shock\n')
        f.write(f';\n\n\n')
# Call the function
write_dict_to_file(ss_dict, 't_vars.m')

In [13]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('initval;\n')
        for key, value in ss_dict.items():
            f.write(f'{key}={value};\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_ss.m')

In [14]:
def write_dict_to_file(params, filename):
    
    with open(filename, 'w') as f:
        f.write('parameters ')
        f.write(','.join(f'{key}' for key in params))
        f.write(';\n\n')
        for key, value in params.items():
            f.write(f'{key}={value};\n')

# Call the function
write_dict_to_file(model_params, 't_parameters.m')

In [15]:
def write_dict_to_file(ss_dict, filename):
    #variance_list = list(shock_params.values())[:3]
    with open(filename, 'w') as f:
        f.write('shocks;\n')
        i=0
        for key, value in ss_shock.items():
            f.write(f'var {key}_shock=var_{key};\n')
            i+=1
        f.write(f'\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_shocks.m')