In [1]:
from scipy.optimize import root
import numpy as np

In [2]:
params = {
    'eps': 1.5,
    'tht': 1,
    'alf': .5,
    'bet': .9,
    'om_0': 1,
    'om_1': 1,
    'om_2': 1,
    'delt': .05
}



In [3]:
ss_shock = {
    'a_0': 0,
    'a_1': 0,
    'a_2': 0
}

In [4]:
shock_params = {
    'var_a_0': .5,
    'var_a_1': .6,
    'var_a_2': .7,
    'rho_a_0': .9,
    'rho_a_1': .9,
    'rho_a_2': .9
}

In [5]:
ss_params = {**params, **ss_shock}
model_params = {**params, **shock_params}

In [6]:
model_params

{'eps': 1.5,
 'tht': 1,
 'alf': 0.5,
 'bet': 0.9,
 'om_0': 1,
 'om_1': 1,
 'om_2': 1,
 'delt': 0.05,
 'var_a_0': 0.5,
 'var_a_1': 0.6,
 'var_a_2': 0.7,
 'rho_a_0': 0.9,
 'rho_a_1': 0.9,
 'rho_a_2': 0.9}

In [7]:
print(','.join(f'{key}' for key in ss_params))

eps,tht,alf,bet,om_0,om_1,om_2,delt,a_0,a_1,a_2


In [8]:
print(','.join(f'{key}' for key in model_params))

eps,tht,alf,bet,om_0,om_1,om_2,delt,var_a_0,var_a_1,var_a_2,rho_a_0,rho_a_1,rho_a_2


In [9]:
def assign_params(ss_params):
    a_0 = ss_params['a_0']
    a_1 = ss_params['a_1']
    a_2 = ss_params['a_2']
    alf = ss_params['alf']
    delt = ss_params['delt']
    om_0 = ss_params['om_0']
    om_1 = ss_params['om_1']
    om_2 = ss_params['om_2']
    eps = ss_params['eps']
    tht = ss_params['tht']
    bet = ss_params['bet']
   
    return eps,tht,alf,bet,om_0,om_1,om_2,delt,a_0,a_1,a_2



In [10]:
def equations(vars, params):
	n_0,n_1,n_2,s_0,s_1,s_2,k,k_0,k_1,k_2,c_0,c_1,c_2 = vars
	eps,tht,alf,bet,om_0,om_1,om_2,delt,a_0,a_1,a_2 = assign_params(params)
	ph=(om_0*c_0**((eps-1)/eps)+om_1*c_1**((eps-1)/eps)+om_2*c_2**((eps-1)/eps)	)**((1-tht*eps)/(eps-1))

	v_0=om_0*c_0**(-1/eps)*ph
	v_1=om_1*c_1**(-1/eps)*ph
	v_2=om_2*c_2**(-1/eps)*ph

	fn_0=np.exp(a_0)*(1-alf)*(s_0/n_0)**alf*k**alf
	fn_1=np.exp(a_1)*(1-alf)*(s_1/n_1)**alf*k**alf
	fn_2=np.exp(a_2)*(1-alf)*(s_2/n_2)**alf*k**alf
 
	fs_0=np.exp(a_0)*alf*(n_0/s_0)**(1-alf)*k**alf
	fs_1=np.exp(a_1)*alf*(n_1/s_1)**(1-alf)*k**alf
	fs_2=np.exp(a_2)*alf*(n_2/s_2)**(1-alf)*k**alf

	eq1=n_0+n_1+n_2-1
	eq2=s_0+s_1+s_2-1
 
	eq3=k_0-s_0/n_0*k
	eq4=k_1-s_1/n_1*k
	eq5=k_2-s_2/n_2*k
	
	eq6=v_1*fn_1-v_0*fn_0
	eq7=v_2*fn_2-v_0*fn_0
 
	eq8=v_1*fs_1-v_0*fs_0
	eq9=v_2*fs_2-v_0*fs_0
 
	
 
	eq10=bet*(fs_0/k+1-delt)-1
	
	eq11=c_0-np.exp(a_0)*n_0**(1-alf)*s_0**alf*k**alf-(1-delt)*k+k
	eq12=c_1-np.exp(a_1)*n_1**(1-alf)*s_1**alf*k**alf
	eq13=c_2-np.exp(a_2)*n_2**(1-alf)*s_2**alf*k**alf
	
	

	return [eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9,eq10,eq11,eq12,eq13]


In [11]:
initial_guess = [.3,.3,.3,.3,.3,.3,.3,.3,.3,.3,.3,.3,.3]
def solve_equations(params):
    
    sol = root(equations, initial_guess, args=(ss_params,))
    
    # Extract the solution vector
    n_0,n_1,n_2,s_0,s_1,s_2,k,k_0,k_1,k_2,c_0,c_1,c_2 = sol.x
    a_0=0
    a_1=0
    a_2=0
    ss_dict = {
    'n_0': n_0,
    'n_1': n_1,
    'n_2': n_2,
    's_0': s_0,
    's_1': s_1,
    's_2': s_2,    
    'k': k,
    'k_0': k_0,
    'k_1': k_1,
    'k_2': k_2,
    'c_0': c_0,
    'c_1': c_1,
    'c_2': c_2,
    'a_0': a_0,
    'a_1': a_1,
    'a_2': a_2
    }
    return sol, ss_dict
    

# Call the wrapper function
sol, ss_dict=solve_equations(ss_params)
print(sol)
ss_dict


 message: The solution converged.
 success: True
  status: 1
     fun: [-1.110e-16  0.000e+00 ...  9.068e-11 -4.988e-12]
       x: [ 4.368e-01  2.816e-01 ...  8.740e-01  8.740e-01]
    nfev: 47
    fjac: [[-1.828e-01  3.907e-10 ... -1.847e-02 -1.850e-02]
           [-1.066e-01 -3.341e-10 ...  1.002e-01  1.570e-02]
           ...
           [-1.211e-02  6.108e-03 ... -3.305e-03 -3.307e-03]
           [-1.300e-01  6.553e-02 ... -3.546e-02 -3.547e-02]]
       r: [-5.470e+00 -1.199e-01 ...  6.215e-01 -1.169e-01]
     qtf: [ 2.406e-09 -1.912e-09 ...  2.187e-11  2.347e-10]


{'n_0': 0.4367816092785867,
 'n_1': 0.2816091953452936,
 'n_2': 0.2816091953761196,
 's_0': 0.436781609279106,
 's_1': 0.28160919534503404,
 's_2': 0.28160919537586,
 'k': 9.631391200688238,
 'k_0': 9.631391200514672,
 'k_1': 9.631391200814955,
 'k_2': 9.631391200814951,
 'c_0': 0.8739595721069313,
 'c_1': 0.8739595718396,
 'c_2': 0.8739595718395994,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [12]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('var \n')
        for key, value in ss_dict.items():
            f.write(f'{key}\n')
        f.write(f';\n\n\n')
        f.write('varexo \n')
        for key, value in ss_shock.items():
            f.write(f'{key}_shock\n')
        f.write(f';\n\n\n')
# Call the function
write_dict_to_file(ss_dict, 't_vars.m')

In [13]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('initval;\n')
        for key, value in ss_dict.items():
            f.write(f'{key}={value};\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_ss.m')

In [14]:
def write_dict_to_file(params, filename):
    
    with open(filename, 'w') as f:
        f.write('parameters ')
        f.write(','.join(f'{key}' for key in params))
        f.write(';\n\n')
        for key, value in params.items():
            f.write(f'{key}={value};\n')

# Call the function
write_dict_to_file(model_params, 't_parameters.m')

In [15]:
def write_dict_to_file(ss_dict, filename):
    #variance_list = list(shock_params.values())[:3]
    with open(filename, 'w') as f:
        f.write('shocks;\n')
        i=0
        for key, value in ss_shock.items():
            f.write(f'var {key}_shock=var_{key};\n')
            i+=1
        f.write(f'\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_shocks.m')