In [1]:
from scipy.optimize import root
import numpy as np
import pickle

In [2]:
with open('mf1.pkl', 'rb') as f:
    ss_params,model_params,ss_shock = pickle.load(f)


In [3]:
def assign_params(ss_params):
    a_0 = ss_params['a_0']
    a_1 = ss_params['a_1']
    a_2 = ss_params['a_2']
    alf = ss_params['alf']
    delt = ss_params['delt']
    om_0 = ss_params['om_0']
    om_1 = ss_params['om_1']
    om_2 = ss_params['om_2']
    eps = ss_params['eps']
    tht = ss_params['tht']
    bet = ss_params['bet']
    psi_k = ss_params['psi_k']
    psi_n = ss_params['psi_n']
    return eps,tht,alf,bet,om_0,om_1,om_2,delt,psi_k,psi_n,a_0,a_1,a_2


In [4]:
ss_params

{'eps': 1,
 'tht': 1,
 'alf': 0.3,
 'bet': 0.9,
 'om_0': 0.3,
 'om_1': 0.4,
 'om_2': 0.4,
 'delt': 0.05,
 'psi_n': 1,
 'psi_k': 1,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [5]:
def equations(vars, params):
	n_0,n_1,n_2,s_0,s_1,s_2,k,c_0,c_1,c_2,i = vars
	eps,tht,alf,bet,om_0,om_1,om_2,delt,psi_k,psi_n,a_0,a_1,a_2 = assign_params(params)
 
	
	#ph=(om_0*c_0**((eps-1)/eps)+om_1*c_1**((eps-1)/eps)+om_2*c_2**((eps-1)/eps)	)**((1-tht*eps)/(eps-1))

	v_0=om_0*c_0**(-1/eps)
	v_1=om_1*c_1**(-1/eps)
	v_2=om_2*c_2**(-1/eps)

	fn_0=np.exp(a_0)*(1-alf)*(s_0/n_0)**alf*k**alf
	fn_1=np.exp(a_1)*(1-alf)*(s_1/n_1)**alf*k**alf
	fn_2=np.exp(a_2)*(1-alf)*(s_2/n_2)**alf*k**alf
 
	fs_0=np.exp(a_0)*alf*(n_0/s_0)**(1-alf)*k**alf
	fs_1=np.exp(a_1)*alf*(n_1/s_1)**(1-alf)*k**alf
	fs_2=np.exp(a_2)*alf*(n_2/s_2)**(1-alf)*k**alf
  
	x_10=fn_0
	x_11=fn_1
	x_12=fn_2

	x_20=0
	x_21=0
	x_22=0
 
	z_1=1
	z_2=1-delt
 
	eq1=n_0+n_1+n_2-1
	eq2=s_0+s_1+s_2-1
	eq3=v_1*fn_1-v_0*fn_0
	eq4=v_2*fn_2-v_0*fn_0
	eq5=v_1*fs_1-v_0*fs_0
	eq6=v_2*fs_2-v_0*fs_0
	eq7=bet*(fs_0/k+z_2)-1
	eq8=(1-delt)*k+i-k
	eq9=c_0+i-np.exp(a_0)*n_0**(1-alf)*s_0**alf*k**alf
	eq10=c_1-np.exp(a_1)*n_1**(1-alf)*s_1**alf*k**alf
	eq11=c_2-np.exp(a_2)*n_2**(1-alf)*s_2**alf*k**alf
	
	return [eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9,eq10,eq11]


In [6]:
initial_guess = [1,1,.3,.3,.3,.3,3,1,1,1,.1]
def solve_equations(params):
    
    sol = root(equations, initial_guess, args=(ss_params,))
    
    # Extract the solution vector
    n_0,n_1,n_2,s_0,s_1,s_2,k,c_0,c_1,c_2,i = sol.x
    #eps,tht,alf,bet,om_0,om_1,om_2,delt,psi_k,psi_n,a_0,a_1,a_2 = assign_params(params)
    a_0=0
    a_1=0
    a_2=0
    ss_dict = {
    #'n_0': n_0,
    'n_1': n_1,
    'n_2': n_2,
    #'s_0': s_0,
    's_1': s_1,
    's_2': s_2,    
    'k': k,
    'c_0': c_0,
    'c_1': c_1,
    'c_2': c_2,
    'i': i,
    'a_0': a_0,
    'a_1': a_1,
    'a_2': a_2
    }
    return sol, ss_dict
    

#Call the wrapper function
sol, ss_dict=solve_equations(ss_params)
print(sol)
ss_dict


 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00  0.000e+00 -2.236e-10 -2.902e-10 -3.362e-11
           -3.113e-11 -2.643e-13  0.000e+00  2.408e-11  6.326e-12
            6.145e-12]
       x: [ 3.404e-01  3.298e-01  3.298e-01  3.404e-01  3.298e-01
            3.298e-01  2.431e+00  3.228e-01  4.305e-01  4.305e-01
            1.215e-01]
    nfev: 45
    fjac: [[ 4.519e-01 -3.944e-10 ... -1.894e-02 -2.603e-02]
           [ 6.121e-01  2.215e-10 ... -4.665e-01 -8.328e-03]
           ...
           [ 3.005e-01  1.417e-01 ...  2.118e-01  5.032e-01]
           [-1.012e-01  9.349e-02 ... -1.207e-02 -1.301e-03]]
       r: [ 2.213e+00 -6.926e-01 ... -3.760e-01 -6.051e-01]
     qtf: [-4.033e-09  3.877e-10  3.552e-09  1.358e-09 -2.473e-10
           -2.166e-09  4.609e-10  8.366e-10 -1.453e-09  1.247e-09
            1.968e-10]


C:\Users\blankenw\AppData\Local\Temp\ipykernel_11528\4277247800.py:13: RuntimeWarning: invalid value encountered in scalar power
  fn_1=np.exp(a_1)*(1-alf)*(s_1/n_1)**alf*k**alf
C:\Users\blankenw\AppData\Local\Temp\ipykernel_11528\4277247800.py:17: RuntimeWarning: invalid value encountered in scalar power
  fs_1=np.exp(a_1)*alf*(n_1/s_1)**(1-alf)*k**alf
C:\Users\blankenw\AppData\Local\Temp\ipykernel_11528\4277247800.py:40: RuntimeWarning: invalid value encountered in scalar power
  eq10=c_1-np.exp(a_1)*n_1**(1-alf)*s_1**alf*k**alf


{'n_1': 0.32978056428764774,
 'n_2': 0.32978056431365665,
 's_1': 0.3297805642777271,
 's_2': 0.3297805642756063,
 'k': 2.430570548816265,
 'c_0': 0.3228485122806911,
 'c_1': 0.43046468313221586,
 'c_2': 0.43046468315496894,
 'i': 0.12152852744081348,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [7]:
ss_dict

{'n_1': 0.32978056428764774,
 'n_2': 0.32978056431365665,
 's_1': 0.3297805642777271,
 's_2': 0.3297805642756063,
 'k': 2.430570548816265,
 'c_0': 0.3228485122806911,
 'c_1': 0.43046468313221586,
 'c_2': 0.43046468315496894,
 'i': 0.12152852744081348,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [8]:
# Call the wrapper function
#sol, ss_dict = solve_equations(ss_params)

In [9]:
# Replace values with their logarithms except for the key 'i'
for key in ss_dict:
	if  key not in ['i', 'a_0','a_1','a_2']:
		ss_dict[key] = np.log(ss_dict[key])



In [10]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('var \n')
        for key, value in ss_dict.items():
            f.write(f'{key}\n')
        f.write(f';\n\n\n')
        f.write('varexo \n')
        for key, value in ss_shock.items():
            f.write(f'{key}_shock\n')
        f.write(f';\n\n\n')
# Call the function
write_dict_to_file(ss_dict, 't_vars.m')

In [11]:
def write_dict_to_file(ss_dict, filename):
    with open(filename, 'w') as f:
        f.write('initval;\n')
        for key, value in ss_dict.items():
            f.write(f'{key}={value};\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_ss.m')

In [12]:
ss_dict

{'n_1': -1.1093278024074744,
 'n_2': -1.109327802328607,
 's_1': -1.1093278024375568,
 's_2': -1.1093278024439879,
 'k': 0.8881260235442675,
 'c_0': -1.1305720680023872,
 'c_1': -0.842889995338523,
 'c_2': -0.842889995285666,
 'i': 0.12152852744081348,
 'a_0': 0,
 'a_1': 0,
 'a_2': 0}

In [13]:
def write_dict_to_file(params, filename):
    
    with open(filename, 'w') as f:
        f.write('parameters ')
        f.write(','.join(f'{key}' for key in params))
        f.write(';\n\n')
        for key, value in params.items():
            f.write(f'{key}={value};\n')

# Call the function
write_dict_to_file(model_params, 't_parameters.m')

In [14]:
def write_dict_to_file(ss_dict, filename):
    #variance_list = list(shock_params.values())[:3]
    with open(filename, 'w') as f:
        f.write('shocks;\n')
        i=0
        for key, value in ss_shock.items():
            f.write(f'var {key}_shock=var_{key};\n')
            i+=1
        f.write(f'\n')
        f.write(f'end;\n\n\n')        
# Call the function
write_dict_to_file(ss_dict, 't_shocks.m')

In [15]:
with open('mf2.pkl', 'wb') as f:
    pickle.dump((ss_dict), f)